[package]
name = "juno-helpers"
version = { workspace = true }
authors = ["Marc <marc@yieldmos.com>"]
description = "Utility functions for Juno interaction used by Yieldmos outpost contracts"
edition = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cosmos-sdk-proto = { workspace = true }
cw20 = { workspace = true }
wyndex = { workspace = true }
wyndex-multi-hop = { workspace = true }
outpost-utils = { workspace = true }
cw20-stake = { workspace = true }
cw20-vesting = { workspace = true }
wynd-stake = { workspace = true }
wynd-helpers = { workspace = true }
white-whale = { workspace = true }
balance-token-swap = { workspace = true }
bond-router = { workspace = true }
