[package]
name = "ymos-destinations"
version = { workspace = true }
authors = ["Marc <marc@yieldmos.com>"]
description = "Generalized message generators and compounding preferences used by Yieldmos outpost contracts"
edition = { workspace = true }

[features]
juno = [
    "dep:wyndex",
    "dep:wyndex-multi-hop",
    "dep:wynd-stake",
    "dep:wynd-helpers",
    "dep:balance-token-swap",
    "dep:bond-router",
    "dep:terraswap-helpers",
]
sail = ["dep:wynd-helpers", "dep:terraswap-helpers", "dep:eris"]
migaloo = ["dep:furnace", "dep:terraswap-helpers", "dep:eris"]
osmosis = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cosmos-sdk-proto = { workspace = true }
cw20 = { workspace = true }
outpost-utils = { workspace = true }
cw20-stake = { workspace = true }
cw20-vesting = { workspace = true }
white-whale = { workspace = true }
wyndex = { workspace = true, optional = true }
wyndex-multi-hop = { workspace = true, optional = true }
wynd-stake = { workspace = true, optional = true }
wynd-helpers = { workspace = true, optional = true }
terraswap-helpers = { workspace = true, optional = true }
balance-token-swap = { workspace = true, optional = true }
bond-router = { workspace = true, optional = true }
cw-grant-spec = { workspace = true }
furnace = { workspace = true, optional = true }
eris = { workspace = true, optional = true }
