[package]
name = "membrane-helpers"
version = { workspace = true }
authors = ["Marc <marc@yieldmos.com>"]
description = "Utility functions for Membrane Finance interaction used by Yieldmos outpost contracts"
edition = { workspace = true }

[dependencies]
cw-storage-plus = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cosmos-sdk-proto = { workspace = true }
cw20 = { workspace = true }
outpost-utils = { workspace = true }
osmosis-std = { workspace = true }
osmosis-destinations = { workspace = true }
# swaprouter = { workspace = true }
cw-grant-spec = { workspace = true }
osmosis-helpers = { workspace = true }
membrane = { git = "https://github.com/MembraneFinance/membrane-core.git", branch = "oracle_pricing" }
